main = ".open-next/worker.js"
name = "trading-sto"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
NEXT_PUBLIC_DEBUG = "true"

[limits]
cpu_ms = 300000

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
[[routes]]
pattern = "unitoken.trade"
custom_domain = true