import { resourceNode } from "./common";

export const TOOL_NODE_N8N_DESCRIPTION = resourceNode({
  displayName: "Tool",
  name: "tool_node",
  icon: "fa:wrench",
  group: ["transform"],
  description: "Tool definition — connect to an Agent node's Tools input.",
  properties: [
    {
      displayName: "Tool kind",
      name: "toolKind",
      type: "options",
      default: "http-request",
      options: [
        { name: "HTTP Request", value: "http-request" },
        { name: "Code", value: "code" },
        { name: "Save RAG", value: "save-rag" },
        { name: "Get RAG", value: "get-rag" },
        { name: "Get DB Info", value: "get-db-info" },
      ],
    },
    {
      displayName: "Tool name",
      name: "toolName",
      type: "string",
      default: "",
    },
    {
      displayName: "Description",
      name: "toolDescription",
      type: "string",
      typeOptions: { rows: 3 },
      default: "",
    },
    {
      displayName: "URL",
      name: "url",
      type: "string",
      default: "",
      displayOptions: { show: { toolKind: ["http-request"] } },
    },
    {
      displayName: "Code",
      name: "code",
      type: "string",
      typeOptions: { rows: 4 },
      default: "",
      displayOptions: { show: { toolKind: ["code"] } },
    },
    {
      displayName: "Chunk size",
      name: "chunkSize",
      type: "number",
      default: 800,
      displayOptions: { show: { toolKind: ["save-rag"] } },
    },
    {
      displayName: "Chunk overlap",
      name: "chunkOverlap",
      type: "number",
      default: 120,
      displayOptions: { show: { toolKind: ["save-rag"] } },
    },
    {
      displayName: "Top K",
      name: "topK",
      type: "number",
      default: 5,
      displayOptions: { show: { toolKind: ["get-rag"] } },
    },
    {
      displayName: "Score threshold",
      name: "scoreThreshold",
      type: "number",
      default: 0.65,
      displayOptions: { show: { toolKind: ["get-rag"] } },
    },
    {
      displayName: "Include metadata",
      name: "includeMetadata",
      type: "boolean",
      default: true,
      displayOptions: { show: { toolKind: ["get-rag"] } },
    },
    {
      displayName: "Sample row limit",
      name: "sampleRowLimit",
      type: "number",
      default: 10,
      displayOptions: { show: { toolKind: ["get-db-info"] } },
    },
    {
      displayName: "SQL history limit",
      name: "sqlHistoryLimit",
      type: "number",
      default: 10,
      displayOptions: { show: { toolKind: ["get-db-info"] } },
    },
    {
      displayName: "Label",
      name: "label",
      type: "string",
      default: "Tool",
    },
  ],
});
